  
        CREATE OR REPLACE PIPE 
        SALES_CONVERSATIONS_DB.CONVERSATIONS.CONVERSATIONS_PIPE 
         AUTO_INGEST = TRUE  COMMENT = 'Snowpipe for automatically loading sales conversations'  AS 
        COPY INTO 
        SALES_CONVERSATIONS_DB.CONVERSATIONS.SALES_CONVERSATIONS 
        FROM 
        @SALES_CONVERSATIONS_DB.CONVERSATIONS.CONVERSATIONS_STAGE/SALES_CONVERSATIONS 
        FILE_FORMAT = SALES_CONVERSATIONS_DB.CONVERSATIONS.CSV_FORMAT 
        