      
        CREATE SECURITY INTEGRATION TEST_EXT_SECURITY_INT 
        TYPE = API_AUTHENTICATION 
        AUTH_TYPE = OAUTH2 
        ENABLED = TRUE
         OAUTH_TOKEN_ENDPOINT = 'https://test-auth-server.example.com/oauth/token' OAUTH_CLIENT_AUTH_METHOD = 'CLIENT_SECRET_BASIC' OAUTH_CLIENT_ID = 'test_client_123' OAUTH_CLIENT_SECRET = 'test_secret_456' OAUTH_ACCESS_TOKEN_VALIDITY = 3600 COMMENT = 'NONE' 