CREATE CORTEX SEARCH SERVICE SALES_CONV.CONVERSATIONS.SALES_CONVERSATIONS_SEARCH 
        ON CONVERSATION_TEXT 
        ATTRIBUTES SALES_REP_REGION,SALES_REP_NAME,CUSTOMER_NAME,CUSTOMER_ID,CONVERSATION_DATE
        WAREHOUSE = COMPUTE_WH
        TARGET_LAG = '20 MINUTES'
         COMMENT = 'Cortex Search service for natural language querying of sales conversations' AS (SELECT CONVERSATION_TEXT, SALES_REP_REGION, SALES_REP_NAME, CUSTOMER_NAME, CUSTOMER_ID, CONVERSATION_DATE FROM SALES_CONV.CONVERSATIONS.SALES_INTERACTIONS)