      CREATE USER EFFICIENT_BOT  FIRST_NAME = 'efficient' 
 LAST_NAME = 'bot' 
 EMAIL = 'efficientbot@gmail.com' 
 MUST_CHANGE_PASSWORD = TRUE 
 DEFAULT_WAREHOUSE = ANALYTICS_WH 
 DEFAULT_ROLE = ANALYTICS_ROLE 
