        
        CREATE SECURITY INTEGRATION TEST_AUTH_CODE_INT 
        TYPE = API_AUTHENTICATION 
        AUTH_TYPE = OAUTH2 
        ENABLED = TRUE
         OAUTH_TOKEN_ENDPOINT = 'https://test-auth.example.com/oauth2/token' OAUTH_CLIENT_AUTH_METHOD = 'CLIENT_SECRET_POST' OAUTH_CLIENT_ID = 'auth_code_client_789' OAUTH_CLIENT_SECRET = 'auth_code_secret_789' OAUTH_ACCESS_TOKEN_VALIDITY = 7200 OAUTH_AUTHORIZATION_ENDPOINT = 'https://test-auth.example.com/oauth2/authorize' OAUTH_REFRESH_TOKEN_VALIDITY = 86400 COMMENT = 'NONE' 