      
        CREATE SECURITY INTEGRATION TEST_CLIENT_CRED_SIMPLE 
        TYPE = API_AUTHENTICATION 
        AUTH_TYPE = OAUTH2 
        ENABLED = TRUE
         OAUTH_TOKEN_ENDPOINT = 'https://test-api.example.com/oauth/token' OAUTH_CLIENT_AUTH_METHOD = 'CLIENT_SECRET_POST' OAUTH_CLIENT_ID = 'scoped_client_999' OAUTH_CLIENT_SECRET = 'scoped_secret_999' OAUTH_ACCESS_TOKEN_VALIDITY = 3600 COMMENT = 'NONE' 