       
        CREATE OR REPLACE FILE FORMAT  
        SALES_CONVERSATIONS_DB.CONVERSATIONS.CSV_FORMAT 
         TYPE = CSV 
 FIELD_DELIMITER = ',' 
 SKIP_HEADER = 1 
 TRIM_SPACE = TRUE 
 ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE 
 EMPTY_FIELD_AS_NULL = TRUE 
 COMMENT = 'CSV file format for sales conversations data' 