      
        CREATE SECURITY INTEGRATION TEST_JWT_INT 
        TYPE = API_AUTHENTICATION 
        AUTH_TYPE = OAUTH2 
        ENABLED = TRUE
         OAUTH_TOKEN_ENDPOINT = 'https://test-jwt.example.com/oauth/token' OAUTH_CLIENT_AUTH_METHOD = 'CLIENT_SECRET_BASIC' OAUTH_CLIENT_ID = 'jwt_client_456' OAUTH_CLIENT_SECRET = 'jwt_secret_456' OAUTH_ACCESS_TOKEN_VALIDITY = 1800 COMMENT = 'NONE' 