    CREATE OR REPLACE STAGE SALES_CONVERSATIONS_DB.CONVERSATIONS.CONVERSATIONS_STAGE  FILE_FORMAT = SALES_CONVERSATIONS_DB.CONVERSATIONS.CSV_FORMAT 
 COMMENT = 'External stage for loading sales conversations data' 
 URL = 's3://sf-bucket-snowchain' 
 STORAGE_INTEGRATION = S3_INT 
